import tempfile
import unittest
from pathlib import Path
from unittest import mock

from friday_core import (CoreUpgradeHarness, DeploymentManager, GraphStore,
                         TaskService)


class CoreUpgradeHarnessTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        (self.root / "friday_core").mkdir()
        (self.root / "tests").mkdir()
        (self.root / "server.py").write_text("VALUE = 1\n")
        (self.root / "tests/test_existing.py").write_text("# protected\n")
        self.graph = GraphStore(self.root / "state/friday.db")
        self.tasks = TaskService(self.graph)
        deployer = DeploymentManager(self.graph, self.root, ["true"])
        self.harness = CoreUpgradeHarness(
            self.graph, self.tasks, deployer, self.root, pi_binary="/bin/true")

    def tearDown(self):
        self.tmp.cleanup()

    def test_worker_sees_only_allowlisted_source(self):
        (self.root / "secret.txt").write_text("not for worker")
        workspace = self.root / "stage"
        workspace.mkdir()
        before = self.harness._copy_source(workspace)

        self.assertIn("server.py", before)
        self.assertIn("tests/test_existing.py", before)
        self.assertFalse((workspace / "secret.txt").exists())

    def test_existing_tests_cannot_be_changed_or_deleted(self):
        workspace = self.root / "stage"
        workspace.mkdir()
        before = self.harness._copy_source(workspace)
        (workspace / "tests/test_existing.py").write_text("# weakened\n")
        with self.assertRaisesRegex(RuntimeError, "may not alter existing test"):
            self.harness._collect_changes(workspace, before)

        (workspace / "tests/test_existing.py").unlink()
        with self.assertRaisesRegex(RuntimeError, "may not delete"):
            self.harness._collect_changes(workspace, before)

    def test_new_focused_test_and_core_change_are_collected(self):
        workspace = self.root / "stage"
        workspace.mkdir()
        before = self.harness._copy_source(workspace)
        (workspace / "server.py").write_text("VALUE = 2\n")
        (workspace / "tests/test_upgrade_feature.py").write_text("# new test\n")

        changes = self.harness._collect_changes(workspace, before)

        self.assertEqual(set(changes), {"server.py", "tests/test_upgrade_feature.py"})

    def test_generated_cache_artifacts_are_ignored(self):
        workspace = self.root / "stage"
        workspace.mkdir()
        before = self.harness._copy_source(workspace)
        (workspace / "server.py").write_text("VALUE = 2\n")
        bytecode = workspace / "friday_core/__pycache__/worker.cpython-313.pyc"
        bytecode.parent.mkdir(parents=True)
        bytecode.write_bytes(b"generated bytecode")
        pytest_cache = workspace / "tests/.pytest_cache/v/cache/nodeids"
        pytest_cache.parent.mkdir(parents=True)
        pytest_cache.write_text("[]\n")

        changes = self.harness._collect_changes(workspace, before)

        self.assertEqual(changes, {"server.py": "VALUE = 2\n"})
        self.assertFalse(bytecode.exists())
        self.assertFalse(pytest_cache.exists())

    def test_unexpected_worker_file_cannot_influence_verification(self):
        workspace = self.root / "stage"
        workspace.mkdir()
        before = self.harness._copy_source(workspace)
        (workspace / "sitecustomize.py").write_text(
            "raise SystemExit('test bypass')\n")

        with self.assertRaisesRegex(RuntimeError, "outside the promotion bundle"):
            self.harness._collect_changes(workspace, before)

    def test_worker_symlinks_cannot_escape_the_staging_tree(self):
        workspace = self.root / "stage"
        workspace.mkdir()
        before = self.harness._copy_source(workspace)
        (workspace / "server.py").unlink()
        (workspace / "server.py").symlink_to("/etc/passwd")

        with self.assertRaisesRegex(RuntimeError, "symlink"):
            self.harness._collect_changes(workspace, before)

    def test_untrusted_candidate_is_never_automatically_promoted(self):
        task_id, _ = self.tasks.create("prepare an upgrade", {"version": 0})
        with mock.patch.object(
                self.harness, "_pi_command",
                return_value=(["true"], self.root / "bridge.sock")), \
             mock.patch.object(self.harness, "_run_pi"), \
             mock.patch.object(
                 self.harness, "_collect_changes",
                 return_value={"server.py": "VALUE = 2\n"}), \
             mock.patch.object(
                 self.harness, "_verify_staged",
                 return_value="informative test output\nOK\n"), \
             mock.patch.object(
                 self.harness.deployer, "stage_bundle") as promote:
            result = self.harness.upgrade(
                "prepare a safe change", task_id=task_id)

        promote.assert_not_called()
        self.assertEqual(result["status"], "awaiting_review")
        self.assertTrue(Path(result["workspace"]).is_dir())
        self.assertEqual(
            self.harness.list()[0]["status"], "awaiting_review")


if __name__ == "__main__":
    unittest.main()
